apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/rabbitmq
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage
