image:
  repository: yongjulejule/video-streaming
  tag: latest

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: video-streaming.local
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []

env:
  - name: DEBUG
    value: "true"
  - name: PORT
    value: "8080"
  - name: NODE_ENV
    value: "production"
  - name: MONGO_URI
    value: "mongodb://mongo:27017/video?authSource=admin"
  - name: MINIO_ENDPOINT
    value: "http://video-storage:9000"
  - name: MINIO_ACCESS_KEY
    value: "minio"
    # valueFrom:
    #   secretKeyRef:
    #     name: minio-secret
    #     key: accesskey
  - name: MINIO_SECRET_KEY
    value: "minio-sec"
    # valueFrom:
    #   secretKeyRef:
    #     name: minio-secret
    #     key: secretkey
