services:
  video-streaming:
    depends_on:
      - mongo
      - video-storage
      - rabbit
    container_name: video-streaming
    build:
      context: ./app/video-streaming
      dockerfile: Dockerfile
      target: local
    ports:
      - '8080:8080'
    volumes:
      - ./app/video-streaming:/usr/src/app/
    init: true
    restart: always
    environment:
      - DEBUG=true
      - PORT=${PORT:-8080}
      - NODE_ENV=${NODE_ENV:-local}
      - MONGO_URI=mongodb://mongo:password@mongo:27017/video?authSource=admin
      - MINIO_ENDPOINT=http://video-storage:9000

  mongo:
    container_name: video-mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  video-storage:
    image: quay.io/minio/minio
    container_name: video-storage
    ports:
      - '9000:9000' # MinIO API 포트
      - '9001:9001' # MinIO 콘솔 포트
    environment:
      MINIO_ROOT_USER: minioadmin # 관리자 계정 ID
      MINIO_ROOT_PASSWORD: minioadmin # 관리자 비밀번호
    volumes:
      - ./data/min-io:/data # 데이터 persistence를 위한 볼륨
    command: server /data --console-address ":9001"

  rabbit:
    image: rabbitmq:4-management
    container_name: video-mq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
